# Use the official MySQL image from Docker Hub
FROM mysql:latest

# Environment variables for MySQL configuration
ENV MYSQL_ROOT_PASSWORD=1234
ENV MYSQL_DATABASE=${NAME}
ENV MYSQL_USER=${USER}
ENV MYSQL_PASSWORD=${PASSWORD}

# Expose port 3306 for MySQL connections
EXPOSE 3306

# Set the data directory as a volume
VOLUME /var/lib/mysql
